# Generated by Django 2.2.10 on 2020-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200222_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
